trigger:
- main # Pipeline is triggered when changes are pushed to the 'main' branch

pool:
  name: 'Default' 
  demands:
    - Agent.Name -equals HELIPAD

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x' # Ensure this matches your .NET version


- script: cd ASPDOTNETQUIZ4
  displayName: 'Navigate to project directory'

- script: dotnet restore ASPDOTNETQUIZ4/ASPDOTNETQUIZ4.csproj
  displayName: 'Restore dependencies'

- script: dotnet build
  displayName: 'Build project'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish artifacts'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'dotnet-app'
  displayName: 'Publish pipeline artifact'